name: My Frist Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '17'
      - name: Add Node Module
        run : yarn
      - name: Build The Project
        run: yarn build
      - name: Finished build
        run : echo "Hurry"
