name: My Frist Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '17'
      - name: Add Node Module
        run : yarn
      - name: Build The Project
        run: yarn build
      - name: set vercel cli
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"orgId":"wd1zUUv2rizgTq6WkWfEMhgF","projectId":"prj_zgCV6b8xCo7k88ELtwpASRm9QK6D"}' > project.json
      - name: Deploying The Project
        run: yarn deploy
      - name: Finished build
        run : echo "Hurry"
      
